FROM python:latest
ENV PYTHONUNBUFFERED 1
RUN mkdir /src
WORKDIR /src
ADD requirements.txt /src/
RUN pip install -r requirements.txt
ADD manage.py /src/
ADD ./syk/entrypoint.sh /src/
ADD ./syk /src/syk/