# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-07-13 14:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_task_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='task',
            name='object_id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='related_to',
        ),
    ]
