# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-04-02 12:28
from __future__ import unicode_literals

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20170326_1733'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapvertex',
            name='parents',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mapedge',
            name='vertexes',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='mapvertex',
            name='title',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
